apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        name: kafka-producer
        image: localhost:5000/kakfa-producer:latest
        imagePullPolicy: Never
        # resources:
        #   limits:
        #     memory: "20Mi"
        #     cpu: "20m"
        ports:
        - containerPort: 8081
        env:
        - name: "spring.kafka.producer.bootstrap-servers"
          value: my-kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  selector:
    app: kafka-producer
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 31111
